import { describe, expect, it } from 'vitest';
import {
  defineSidebar,
  isSidebarAutoGroup,
  isSidebarDocItem,
  isSidebarGroup,
  isSidebarLinkItem,
} from './sidebar';
import { resolveSidebar } from './sidebar-utils';

const docs = [
  { id: 'getting-started/introduction', data: { title: 'Introduction', order: 0 } },
  { id: 'getting-started/installation', data: { title: 'Installation', order: 1 } },
  { id: 'guides/configuration', data: { title: 'Configuration', order: 0 } },
  {
    id: 'api/reference',
    data: {
      title: 'API Reference',
      order: 0,
      sidebar: { badge: { variant: 'tip' as const, text: 'New' } },
    },
  },
];

describe('defineSidebar', () => {
  it('returns the config unchanged', () => {
    const config = [{ label: 'Test', autogenerate: { directory: 'test' } }];
    expect(defineSidebar(config)).toBe(config);
  });
});

describe('type guards', () => {
  it('identifies link items', () => {
    expect(isSidebarLinkItem({ label: 'Home', link: '/' })).toBe(true);
    expect(isSidebarLinkItem({ slug: 'intro' })).toBe(false);
  });

  it('identifies doc items', () => {
    expect(isSidebarDocItem({ slug: 'guides/intro' })).toBe(true);
    expect(isSidebarDocItem({ label: 'Home', link: '/' })).toBe(false);
  });

  it('identifies groups', () => {
    expect(isSidebarGroup({ label: 'Group', items: [] })).toBe(true);
    expect(isSidebarGroup({ label: 'Auto', autogenerate: { directory: 'x' } })).toBe(false);
  });

  it('identifies auto-groups', () => {
    expect(isSidebarAutoGroup({ label: 'Auto', autogenerate: { directory: 'x' } })).toBe(true);
    expect(isSidebarAutoGroup({ label: 'Group', items: [] })).toBe(false);
  });
});

describe('resolveSidebar', () => {
  it('resolves an autogenerate group', () => {
    const config = defineSidebar([
      { label: 'Getting Started', autogenerate: { directory: 'getting-started' } },
    ]);
    const result = resolveSidebar(config, docs, '/docs/getting-started/introduction');

    expect(result).toHaveLength(1);
    const group = result[0];
    expect(group.type).toBe('group');
    if (group.type === 'group') {
      expect(group.label).toBe('Getting Started');
      expect(group.items).toHaveLength(2);
      expect(group.items[0].type).toBe('link');
      if (group.items[0].type === 'link') {
        expect(group.items[0].label).toBe('Introduction');
        expect(group.items[0].active).toBe(true);
      }
    }
  });

  it('sorts autogenerated items by order', () => {
    const config = defineSidebar([
      { label: 'Getting Started', autogenerate: { directory: 'getting-started' } },
    ]);
    const result = resolveSidebar(config, docs, '/');
    const group = result[0];
    if (group.type === 'group') {
      expect(group.items[0].type === 'link' && group.items[0].label).toBe('Introduction');
      expect(group.items[1].type === 'link' && group.items[1].label).toBe('Installation');
    }
  });

  it('resolves a manual link item', () => {
    const config = defineSidebar([{ label: 'GitHub', link: 'https://github.com' }]);
    const result = resolveSidebar(config, docs, '/');
    expect(result[0].type).toBe('link');
    if (result[0].type === 'link') {
      expect(result[0].label).toBe('GitHub');
      expect(result[0].href).toBe('https://github.com');
    }
  });

  it('marks active link', () => {
    const config = defineSidebar([{ label: 'GitHub', link: '/docs/guides/configuration' }]);
    const result = resolveSidebar(config, docs, '/docs/guides/configuration');
    if (result[0].type === 'link') {
      expect(result[0].active).toBe(true);
    }
  });

  it('carries badge from doc frontmatter in autogenerate', () => {
    const config = defineSidebar([{ label: 'API', autogenerate: { directory: 'api' } }]);
    const result = resolveSidebar(config, docs, '/');
    const group = result[0];
    if (group.type === 'group' && group.items[0].type === 'link') {
      expect(group.items[0].badge?.text).toBe('New');
      expect(group.items[0].badge?.variant).toBe('tip');
    }
  });

  it('returns empty array when config is empty', () => {
    expect(resolveSidebar([], docs, '/')).toEqual([]);
  });

  it('skips doc items that do not exist', () => {
    const config = defineSidebar([{ slug: 'nonexistent/page' }]);
    const result = resolveSidebar(config, docs, '/');
    expect(result).toHaveLength(0);
  });
});
