/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c0138417dc0034cf04a2768557b7e409)
interface __BaseEnv_Env {
	VECTORIZE: VectorizeIndex;
	CHAT_RATE_LIMITER: RateLimit;
	AI: Ai;
	ALLOWED_ORIGINS: "http://localhost:4321,http://localhost:4322,https://kc-docs.casoon.dev,https://kc-courses.casoon.dev,https://docs.knowledge-core.dev,https://courses.knowledge-core.dev";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS">> {}
}
