name = "knowledge-core-chat-worker"
main = "src/index.ts"
compatibility_date = "2025-12-01"
account_id = "817ec8f792eea2e272a0a6cf03ccb57d"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "knowledge-core"
